spring:
  datasource:
    username: ${username}
    url: ${databaseurl}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
